-- 코드를 입력하세요
# SELECT DATE_FORMAT(ONSALE.SALES_DATE, '%Y-%m-%d') as SALES_DATE, ONSALE.PRODUCT_ID, ONSALE.USER_ID, ONSALE.SALES_AMOUNT
#     FROM ONLINE_SALE ONSALE LEFT OUTER JOIN OFFLINE_SALE OFFSALE
#         ON ONSALE.PRODUCT_ID = OFFSALE.PRODUCT_ID
#             WHERE DATE_FORMAT(ONSALE.SALES_DATE, '%Y-%m') = '2022-03' OR DATE_FORMAT(OFFSALE.SALES_DATE, '%Y-%m') = '2022-03'
#                 ORDER BY ONSALE.SALES_DATE, ONSALE.PRODUCT_ID, ONSALE.USER_ID

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
        WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
        
UNION ALL

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
        WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
