-- 코드를 입력하세요
SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
    FROM ANIMAL_INS AI JOIN ANIMAL_OUTS FO
        USING (ANIMAL_ID)
            WHERE AI.SEX_UPON_INTAKE LIKE 'Intact%' AND (FO.SEX_UPON_OUTCOME LIKE 'Spayed%' OR FO.SEX_UPON_OUTCOME LIKE 'Neutered%' )