-- 코드를 입력하세요
SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE), 2) as SCORE
    FROM REST_INFO RI INNER JOIN REST_REVIEW RR
        ON RI.REST_ID = RR.REST_ID
            WHERE RI.ADDRESS LIKE '서울%' AND RR.REVIEW_SCORE is not null
                GROUP BY RI.REST_NAME
                    ORDER BY ROUND(AVG(RR.REVIEW_SCORE), 2) DESC, RI.FAVORITES DESC 
                