SELECT PRODUCT_ID, FD.PRODUCT_NAME, SUM(FO.AMOUNT) * FD.PRICE AS TOTAL_SALES
    FROM FOOD_PRODUCT FD JOIN FOOD_ORDER FO
        USING (PRODUCT_ID)
            WHERE DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m') = '2022-05'
                GROUP BY PRODUCT_ID
                    ORDER BY TOTAL_SALES DESC, PRODUCT_ID