-- 코드를 입력하세요
SELECT II.INGREDIENT_TYPE, SUM(TOTAL_ORDER) as TOTAL_ORDER
    FROM FIRST_HALF FH JOIN ICECREAM_INFO II
        using (FLAVOR)
            GROUP BY II.INGREDIENT_TYPE
                ORDER BY TOTAL_ORDER
        
