-- 코드를 입력하세요
SELECT FO.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
    FROM FOOD_PRODUCT FP JOIN FOOD_ORDER FO
        USING (PRODUCT_ID)
            WHERE DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m') = '2022-05'
                GROUP BY FO.PRODUCT_ID
                    ORDER BY TOTAL_SALES DESC , FP.PRODUCT_ID
                