# -- 코드를 입력하세요
# SELECT
#     FROM USED_GOODS_FILE F JOIN (SELECT * FROM USED_GOODS_BOARD ORDER B)
#         USING (BOARD_ID)

-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', B.BOARD_ID, '/',FILE_ID, FILE_NAME,FILE_EXT ) AS FILE_PATH
    FROM USED_GOODS_FILE F JOIN USED_GOODS_BOARD B
        USING (BOARD_ID)
            WHERE B.VIEWS IN (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
                ORDER BY F.FILE_ID DESC